# Use the official MySQL image
FROM mysql:8.0

# Set environment variables for MySQL root password and database
ENV MYSQL_ROOT_PASSWORD=rootpassword
ENV MYSQL_DATABASE=ses

# Expose the MySQL port
EXPOSE 3306

